In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import validation_curve
df=pd.read_csv('data_vowel_bayes.csv')
df

X1    X2    X3  T
0    700  1500  2600  1
1    550  1550  2400  1
2    700  1500  2600  1
3    700  1600  2700  1
4    550  1600  2600  1
..   ...   ...   ... ..
866  500  1050  2900  6
867  500  1000  3000  6
868  500  1000  2800  6
869  500   900  2800  6
870  500   950  2700  6

[871 rows x 4 columns]

In [6]:
y = df["T"]
x = df.drop(["T"], axis = 1)
x = (x - x.min()) / (x.max() - x.min())

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [8]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [9]:
y_pred = gnb.predict(X_test)


In [12]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test,y_pred,normalize=True)*100)

Gaussian Naive Bayes model accuracy(in %): 84.57142857142857


In [13]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.60      0.50      0.55        12
           2       0.88      0.94      0.91        16
           3       0.94      0.89      0.92        38
           4       0.82      0.93      0.87        29
           5       0.82      0.84      0.83        44
           6       0.85      0.81      0.83        36

    accuracy                           0.85       175
   macro avg       0.82      0.82      0.82       175
weighted avg       0.84      0.85      0.84       175

[[ 6  2  0  0  3  1]
 [ 0 15  0  0  0  1]
 [ 0  0 34  0  4  0]
 [ 1  0  0 27  0  1]
 [ 3  0  2  0 37  2]
 [ 0  0  0  6  1 29]]
